root@ubuntu:/opt/code/github/threefoldtech/minio/test/failures_testsuite# nosetests-3.4 -vs --logging-level=WARNING --progressive-with-bar --rednose testcases/s3/test05_bitrot.py
[Fri23 14:12] - failures.py       :34  :j.<module>           - INFO     - check 626d72f9-8c3a-4e3e-af82-1a4d1f05f3dd on node ac1f6b457630 status
[Fri23 14:12] - failures.py       :34  :j.<module>           - INFO     - check 7981431a-625f-4d59-ad0e-701d567a0b66 on node ac1f6b457630 status
[Fri23 14:12] - failures.py       :34  :j.<module>           - INFO     - check 35a341f9-c3bb-409f-b45d-efa813b900fa on node ac1f6b457344 status
[Fri23 14:12] - failures.py       :34  :j.<module>           - INFO     - check fd99b806-e258-41d7-a401-d17dd09c6c03 on node ac1f6b457338 status
[Fri23 14:12] - failures.py       :34  :j.<module>           - INFO     - check dd709fa4-589d-4a10-a498-0a72c3d778b3 on node ac1f6b457344 status
[Fri23 14:12] - failures.py       :34  :j.<module>           - INFO     - check e091822e-310c-451f-a449-e150f5b6eb5c on node ac1f6b457338 status
[Fri23 14:12] - failures.py       :34  :j.<module>           - INFO     - check 4910b35c-8776-4ed9-b17a-9c789d6077a5 on node ac1f6b457344 status
[Fri23 14:12] - failures.py       :34  :j.<module>           - INFO     - check ce50075b-b3e0-4f8e-94d1-0d2e6f51475d on node ac1f6b457338 status
test001_bitrot ... [Fri23 14:12] - test05_bitrot.py  :12  :j.s3_failures        - INFO     - Make sure all zdbs are up
[Fri23 14:12] - test05_bitrot.py  :56  :j.s3_failures        - INFO     - Get the minio namespaces and get the zdbs location
[Fri23 14:12] - test05_bitrot.py  :60  :j.s3_failures        - INFO     - Get the extra 25% namespaces down
[Fri23 14:12] - failures.py       :154 :j.<module>           - INFO     - stop dd709fa4-589d-4a10-a498-0a72c3d778b3 on node ac1f6b457344
[Fri23 14:12] - failures.py       :154 :j.<module>           - INFO     - stop 626d72f9-8c3a-4e3e-af82-1a4d1f05f3dd on node ac1f6b457630
[Fri23 14:12] - test05_bitrot.py  :66  :j.s3_failures        - INFO     - Upload a file and get its md5sum, should succeed.
[Fri23 14:12] - s3.py             :43  :j.s3demo             - INFO     - get s3 client : ParseResult(scheme='http', netloc='172.29.166.127:1024', path='', params='', query='', fragment='')
[Fri23 14:12] - s3.py             :167 :j.s3demo             - INFO     - create bucket
[Fri23 14:12] - s3.py             :168 :j.s3demo             - INFO     - bucket : 6vomdj8nz6tmum8e
[Fri23 14:12] - s3.py             :186 :j.s3demo             - INFO     - upload 3dqznk63heg2d4s7 file to 6vomdj8nz6tmum8e bucket
[Fri23 14:13] - test05_bitrot.py  :69  :j.s3_failures        - INFO     - Corrupt all data in any zdb location
[Fri23 14:13] - test05_bitrot.py  :74  :j.s3_failures        - INFO     - Get parity zdbs down excluding the corrupted namespace
[Fri23 14:13] - failures.py       :154 :j.<module>           - INFO     - stop 35a341f9-c3bb-409f-b45d-efa813b900fa on node ac1f6b457344
[Fri23 14:13] - failures.py       :154 :j.<module>           - INFO     - stop fd99b806-e258-41d7-a401-d17dd09c6c03 on node ac1f6b457338
[Fri23 14:13] - test05_bitrot.py  :78  :j.s3_failures        - INFO     - Try to download F1, should give wrong md5
[Fri23 14:13] - s3.py             :198 :j.s3demo             - INFO     - Download 3dqznk63heg2d4s7 file form 6vomdj8nz6tmum8e bucket
[Fri23 14:14] - test05_bitrot.py  :82  :j.s3_failures        - INFO     - Get parity zdbs up exculding extra_namespaces zdbs
[Fri23 14:14] - failures.py       :184 :j.<module>           - INFO     - start 35a341f9-c3bb-409f-b45d-efa813b900fa on node ac1f6b457344
[Fri23 14:14] - failures.py       :184 :j.<module>           - INFO     - start fd99b806-e258-41d7-a401-d17dd09c6c03 on node ac1f6b457338
[Fri23 14:14] - test05_bitrot.py  :85  :j.s3_failures        - INFO     - Run the bitrot protection, should succeed
[Fri23 14:14] - test05_bitrot.py  :88  :j.s3_failures        - INFO     - Get parity zdbs down again excluding corrupted namespace zdb
[Fri23 14:14] - failures.py       :154 :j.<module>           - INFO     - stop 35a341f9-c3bb-409f-b45d-efa813b900fa on node ac1f6b457344
[Fri23 14:15] - failures.py       :154 :j.<module>           - INFO     - stop fd99b806-e258-41d7-a401-d17dd09c6c03 on node ac1f6b457338
[Fri23 14:15] - test05_bitrot.py  :91  :j.s3_failures        - INFO     - Download F1 again , should have same md5 as the uploaded file
[Fri23 14:15] - s3.py             :198 :j.s3demo             - INFO     - Download 3dqznk63heg2d4s7 file form 6vomdj8nz6tmum8e bucket
[Fri23 14:15] - test05_bitrot.py  :17  :j.s3_failures        - INFO     - Make sure all zdbs are up
[Fri23 14:15] - failures.py       :184 :j.<module>           - INFO     - start dd709fa4-589d-4a10-a498-0a72c3d778b3 on node ac1f6b457344
[Fri23 14:15] - failures.py       :184 :j.<module>           - INFO     - start 626d72f9-8c3a-4e3e-af82-1a4d1f05f3dd on node ac1f6b457630
[Fri23 14:15] - failures.py       :184 :j.<module>           - INFO     - start 35a341f9-c3bb-409f-b45d-efa813b900fa on node ac1f6b457344
[Fri23 14:15] - failures.py       :184 :j.<module>           - INFO     - start fd99b806-e258-41d7-a401-d17dd09c6c03 on node ac1f6b457338
passed

-----------------------------------------------------------------------------
1 test run in 223.738 seconds (1 test passed)
